on:
  push:
    tags:
      - "v*"

jobs:
  compile_and_release:
    runs-on: ubuntu-latest
    name: Compile TeX to PDF and Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: GitHub Action for LaTeX
        uses: xu-cheng/latex-action@f1ca82cbed861b3534e2997dd584944f55b884ed  # v3.1.0
        with:
          root_file: main.tex
          latexmk_use_lualatex: true

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844  # v0.1.15
        with:
          body: |
            Compiled PDF ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: main.pdf

      - name: Update PDF Link on README
        run: |
          sed -i '/<!-- PDF_LINK_START -->/,/<!-- PDF_LINK_END -->/c\<!-- PDF_LINK_START -->\n最新版のPDFは[こちら](${{ fromJSON(steps.create_release.outputs.assets)[0].browser_download_url }})\n<!-- PDF_LINK_END -->' README.md

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "[Automated] Update PDF link on README for version ${{ github.ref_name }}"
          git pull --rebase origin main
          git push origin HEAD:main
